### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [droneRL2020/Dynamic_obstacle_avoidance_unity#3]
Hello , under what license is this project released under ? Thank-you.

**Comment by droneRL2020** [comment]
Which license do you  mean? Unity? If it is, I am not sure the exact version because I updated a couple of times, but very sure it is one which was free. Also, this is based on ml-agent.

**Comment by suprafun** [comment]
I mean the license of your code :) I would like to learn from it, so I can write my own agent simulator. If this is alright with you. Thank-you.
